---

- name: "configure: Create directory {{ rsnapshot_snapshot_root }}"
  file:
    state: "directory"
    path: "{{ rsnapshot_snapshot_root }}"
    owner: "{{ rsnapshot_snapshot_root_owner }}"
    group: "{{ rsnapshot_snapshot_root_group }}"
    mode: "{{ rsnapshot_snapshot_root_mode }}"

- name: "configure: Create configuration {{ rsnapshot_config_file }}"
  template:
    src: "rsnapshot.conf.j2"
    dest: "{{ rsnapshot_config_file }}"
    owner: "{{ rsnapshot_config_file_owner }}"
    group: "{{ rsnapshot_config_file_group }}"
    mode: "{{ rsnapshot_config_file_mode }}"
    backup: "{{ rsnapshot_backup_conf }}"
    validate: "rsnapshot -c %s configtest"

# EOF
...
